apiVersion: arogoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL:
    targetRevision: HEAD
    path: k8s
  destionation:
    server: https://kubernetes.default.svc
    namespace: mmyapp
