apiVersion: v1
kind: Serivce
metadata:
  name: assessment-tax-client
spec:
  type: NodePort
  selector:
    app: assessment-tax-client
  ports:
  - port: 80
    portocol: TCP
    targetPort: 80
    NodePort: 31000
