apiVersion: v1
kind: Service
metadata:
  name: assessment-tax-client
spec:
  type: NodePort
  selector:
    app: assessment-tax-client
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
